language: python
python:
    - '3.8'

install:
    - pip install -r docker/requirements-dev.txt

env:
    - PYTHONPATH=/usr/bin/python3

script:
    - make tests

# after_success:
#     - ./deploy.sh

# notifications:
#   slack: 
