language: python
python:
    - '3.8'

install:
    - pip install -r requirements-dev.txt

env:
    - PYTHONPATH=/home/me/school/test_project

script:
    - make tests
deploy:
    - provider: heroku
      api_key: $HEROKU_API_KEY
      app: ta2h3nna
      on:
          branch: master
# after_success:
#     - ./deploy.sh

# notifications:
#   slack: 
