language: python
python:
    - '3.8'

install:
    - pip install -r requirements-dev.txt

env:
    - PYTHONPATH=/home/me/school/test_project

script:
    - make tests

# after_success:
#     - ./deploy.sh

# notifications:
#   slack: 
